[package]
name = "wasix_eth_app"
description = ""
version.workspace = true
authors.workspace = true
edition.workspace = true

[[bin]]
name = "wasix_eth"
path = "src/main.rs"

[lints]
workspace = true

[dependencies]
wasix_eth_utils = {workspace = true}
wasix_eth_types = {workspace = true}
wasix_eth_storage = {workspace = true}
wasix_eth_core = {workspace = true}
wasix_eth_execution = {workspace = true}
wasix_eth_p2p = {workspace = true}
wasix_eth_rpc = {workspace = true}

tokio = { workspace = true, features = ["rt-multi-thread", "rt", "macros", "sync", "time", "io-util", "net" , "signal"]}
clap = {workspace = true}
serde_json = {workspace = true}
jsonrpsee = { workspace = true}
hex = { workspace = true }
getrandom = { workspace = true }
http = { workspace = true }
tower = { workspace = true }
futures-util = { workspace = true }
hmac = { workspace = true }
sha2 = { workspace = true }
base64 = { workspace = true }
serde = {workspace = true}
alloy-serde = {workspace = true}
alloy-rlp = {workspace = true}

alloy-json-rpc = {workspace = true}

[target.'cfg(not(target_family = "wasm"))'.dev-dependencies]
tempfile = "3.10"