[package]
name = "wasix-based-evm"
version = "0.1.0"
edition = "2024"

[profile.dev]
panic = "abort"
lto = true

[profile.release]
panic = "abort"
lto = true
codegen-units = 1
[[bin]]
name = "wasix-based-evm"
path = "src/main.rs"

[dependencies]
evm = { path = "../evm", default-features = false, features = ["serde"] }
evm-precompile = { path = "../evm/precompile", default-features = false }
evm-interpreter = { path = "../evm/interpreter", default-features = false }
alloy-primitives = { version = "1.5.7", default-features = false, features = ["serde"] }
alloy-genesis = { version = "=1.6.3", default-features = false }
alloy-consensus = { version = "=1.6.3", default-features = false, features = ["k256", "std"] }
alloy-signer-local = { version = "=1.6.3", default-features = false }
alloy-signer = { version = "=1.6.3", default-features = false }
alloy-network = { version = "=1.6.3", default-features = false }
alloy-json-rpc = { version = "=1.6.3", default-features = false }
alloy-tx-macros = { version = "=1.6.3", default-features = false }
alloy-serde= { version = "=1.6.3", default-features = false }
alloy-eips = { version = "=1.6.3", default-features = false }
alloy-rpc-types = { version = "=1.6.3", default-features = false, features = ["eth", "engine", "admin", "txpool", "jsonrpsee-types"] }
alloy-trie = { version = "0.9.5", default-features = false, features = ["std"] }
alloy-rlp = { version = "0.3.15", default-features = false, features = ["derive"] }
alloy-rlp-derive = { version = "0.3.15", default-features = false}

rand = { version = "=0.8.5", default-features = false }
getrandom = {git = "https://github.com/rust-random/getrandom", tag = "v0.2.15" , default-features = false}
mio = { git = "https://github.com/wasix-org/mio", default-features = false }
h2 = "0.4"
serde_json = { version = "1.0.0", default-features = false, features = ["alloc", "std"] }
async-trait = "0.1.89"
clap = { version = "4.5.4", features = ["derive"] }
thiserror = "2.0.18"
hex = "0.4.3"
anyhow = "1.0.102"
chrono = "0.4"
hmac = "0.12.1"
sha2 = "0.10.8"
futures-util = "0.3.31"
http = "1.1.0"
base64 = "0.22.1"

k256 = { version = "0.13.1", features = ["ecdsa", "arithmetic"] }
serde = { version = "1.0.228", features = ["derive", "std", "serde_derive"] }
#parking_lot = { path = "../parking_lot", default-features = false, features = ["deadlock_detection", "nightly", "default"] }

# When using something different than wasix
#socket2 = { version="0.4.5" , default-features = false, features = ["all"]}
#tokio = { version = "1.47.0", default-features = false, features = [ "rt-multi-thread", "rt", "macros", "sync", "time", "io-util", "net" ] }
#tokio-rustls = { version = "0.24.1", default-features = false, features = ["logging", "tls12", "dangerous_configuration", "secret_extraction"] }
#reqwest = {version = "0.11.8", default-features = false, features = ["json", "serde_json"]}
#jsonrpsee = {version = "0.26.0", default-features = false, features = ["tracing", "server", "jsonrpsee-proc-macros", "jsonrpsee-core", "client-core", "jsonrpsee-types"]}
#rustls = { version = "0.23.31", default-features = false, features = [ "tls12"] }

### frontend
rcgen = "0.13"
axum = { version = "0.7.5", default-features = false, features = ["http1", "json", "query", "tokio", "form"] }
tower = { version = "0.4.13", default-features = false, features = ["util"] }
tower-http = { version = "0.5.2", default-features = false, features = ["fs", "cors"] }
maud = "0.26.0"
once_cell = "1.19.0"
#yew = { version = "0.23", features = ["csr"] }
#dioxus = { version = "0.7.5", features = ["wasm-split", "fullstack"] }

#  WASIX dependencies

# When using wasix
#wasmer = { version = "7.1.0", default-features=false, features=["js-default"]}
wasix = { version = "0.13.1" }

reqwest = {git = "https://github.com/wasix-org/reqwest.git", branch = "rustls-0.21.8", default-features = false, features = ["json", "serde_json"]}
jsonrpsee = {git = "https://github.com/Z4l3s5i0/jsonrpsee", branch = "fix", default-features = false, features = ["server", "jsonrpsee-proc-macros", "jsonrpsee-core", "client-core", "jsonrpsee-types"]}
tokio = { git = "https://github.com/wasix-org/tokio.git", branch = "wasix-1.47.0", default-features = false, features = [ "rt-multi-thread", "rt", "macros", "sync", "time", "io-util", "net", "parking_lot" ] }
tokio-rustls = { git = "https://github.com/wasix-org/tokio-rustls.git", branch = "main", default-features = false, features = ["logging", "tls12", "dangerous_configuration", "secret_extraction"] }
socket2 = { git = "https://github.com/wasix-org/socket2.git", branch = "wasix", default-features = false, features = ["all"]}
rustls = { git = "https://github.com/wasix-org/rustls.git", branch = "wasix-0.23.31", default-features = false, features = [ "tls12"] }




[patch.crates-io]
wasm-bindgen = {git = "https://github.com/wasix-org/wasm-bindgen.git" , branch = "wasi"}
getrandom = {git = "https://github.com/rust-random/getrandom", tag = "v0.2.15" }
mio = { git = "https://github.com/wasix-org/mio" }
#parking_lot = { path = "../parking_lot" }

h2 = { git = "https://github.com/wasix-org/h2", branch = "wasix-0.4.12" }
hyper = { git = "https://github.com/wasix-org/hyper", branch = "v0.14.28" }
ring = {git = "https://github.com/wasix-org/ring", branch = "0.17.7"}
rustls = { git = "https://github.com/wasix-org/rustls.git", branch = "wasix-0.23.31" }
tokio = { git = "https://github.com/wasix-org/tokio.git", branch = "wasix-1.47.0" }
socket2 = { git = "https://github.com/wasix-org/socket2", branch = "wasix" }

tokio-rustls = { git = "https://github.com/wasix-org/tokio-rustls.git", branch = "main" }
libc = { git = "https://github.com/john-sharratt/libc.git", rev = "682f9e91" }
