[package]
name = "wasix-based-evm"
version = "0.1.0"
edition = "2024"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[dependencies]
evm = { path = "../evm", default-features = false }
evm-precompile = { path = "../evm/precompile", default-features = false }
evm-interpreter = { path = "../evm/interpreter", default-features = false }
alloy-primitives = { version = "1.5.7", default-features = false, features = ["serde"] }
alloy-genesis = { version = "=1.6.3", default-features = false }
alloy-consensus = { version = "=1.6.3", default-features = false, features = ["k256", "std"] }
alloy-signer-local = { version = "=1.6.3", default-features = false }
alloy-signer = { version = "=1.6.3", default-features = false }
alloy-network = { version = "=1.6.3", default-features = false }
alloy-json-rpc = { version = "=1.6.3", default-features = false }
alloy-tx-macros = { version = "=1.6.3", default-features = false }
alloy-serde= { version = "=1.6.3", default-features = false }
alloy-eips = { version = "=1.6.3", default-features = false }
alloy-rpc-types = { version = "=1.6.3", default-features = false, features = ["eth", "engine", "admin", "txpool", "jsonrpsee-types"] }
alloy-trie = { version = "0.9.5", default-features = false, features = ["std"] }
alloy-rlp = { version = "0.3.15", default-features = false, features = ["derive"] }
alloy-rlp-derive = { version = "0.3.15", default-features = false}

rand = { version = "=0.8.5", default-features = false }
getrandom = {git = "https://github.com/rust-random/getrandom", tag = "v0.2.15" , default-features = false}
mio = { git = "https://github.com/wasix-org/mio", default-features = false }
h2 = "0.4"
serde_json = { version = "1.0.0", default-features = false, features = ["alloc", "std"] }
async-trait = "0.1.89"
clap = { version = "4.5.4", features = ["derive"] }
thiserror = "2.0.18"
hex = "0.4.3"
anyhow = "1.0.102"
rcgen = "0.13"
#parking_lot = { path = "../parking_lot", default-features = false, features = ["deadlock_detection", "nightly", "default"] }

# When using something different than wasix
#socket2 = { version="0.4.5" , default-features = false, features = ["all"]}
#tokio = { version = "1.47.0", default-features = false, features = [ "rt-multi-thread", "rt", "macros", "sync", "time", "io-util", "net" ] }


#  WASIX dependencies

jsonrpsee = {path = "../jsonrpsee/jsonrpsee", default-features = false, features = ["server", "jsonrpsee-proc-macros", "jsonrpsee-core", "client-core", "jsonrpsee-types"]}
reqwest = {git = "https://github.com/wasix-org/reqwest.git", branch = "rustls-0.21.8", default-features = false, features = ["json", "serde_json"]}
# When using wasix
wasix = { version = "0.13.1" }

tokio = { git = "https://github.com/wasix-org/tokio.git", branch = "wasix-1.47.0", default-features = false, features = [ "rt-multi-thread", "rt", "macros", "sync", "time", "io-util", "net", "parking_lot" ] }
tokio-rustls = { git = "https://github.com/wasix-org/tokio-rustls.git", branch = "main", default-features = false, features = ["logging", "tls12", "dangerous_configuration", "secret_extraction"] }
socket2 = { git = "https://github.com/wasix-org/socket2.git", branch = "wasix", default-features = false, features = ["all"]}
k256 = { version = "0.13.1", features = ["ecdsa", "arithmetic"] }
rustls = { git = "https://github.com/wasix-org/rustls.git", branch = "wasix-0.23.31", default-features = false, features = [ "tls12"] }
serde = { version = "1.0.228", features = ["derive"] }


[patch.crates-io]
wasm-bindgen = {git = "https://github.com/wasix-org/wasm-bindgen.git" , branch = "wasi"}
getrandom = {git = "https://github.com/rust-random/getrandom", tag = "v0.2.15" }
mio = { git = "https://github.com/wasix-org/mio" }
#parking_lot = { path = "../parking_lot" }

h2 = { git = "https://github.com/wasix-org/h2", branch = "wasix-0.4.12" }
hyper = { git = "https://github.com/wasix-org/hyper", branch = "v0.14.28" }
ring = {git = "https://github.com/wasix-org/ring", branch = "0.17.7"}
rustls = { git = "https://github.com/wasix-org/rustls.git", branch = "wasix-0.23.31" }
tokio = { git = "https://github.com/wasix-org/tokio.git", branch = "wasix-1.47.0" }
socket2 = { git = "https://github.com/wasix-org/socket2", branch = "wasix" }

tokio-rustls = { git = "https://github.com/wasix-org/tokio-rustls.git", branch = "main" }
libc = { git = "https://github.com/john-sharratt/libc.git", rev = "682f9e91" }
