[package]
name = "wasix-based-evm"
version = "0.1.0"
description = "Description for package wasix-based-evm"

# See more keys and definitions at https://docs.wasmer.io/registry/manifest

[[module]]
name = "wasix-based-evm"
source = "target/wasm32-wasmer-wasi/debug/wasix-based-evm.wasm"
abi = "wasi"

[module.interfaces]
wasix = "0.1.0"

[[command]]
name = "wasix-based-evm"
module = "wasix-based-evm"
runner = "wasix"
