[package]
name = "wasix-based-evm"
version = "0.1.0"
description = "Description for package wasix-based-evm"
wasmer-extra-flags = "--enable-threads --net --http-client --enable-exceptions --volume ./data-dir:./data-dir --enable-bulk-memory --enable-simd --enable-reference-types --enable-multi-value --llvm --enable-async-threads -v"
# See more keys and definitions at https://docs.wasmer.io/registry/manifest

[[module]]
name = "wasix-based-evm"
source = "target/wasm32-wasmer-wasi/release/wasix-based-evm.wasi.wasm"
abi = "wasi"

[module.interfaces]
wasix = "0.1.0"

#[fs]
#"./data-dir" = "./data-dir"

[[command]]
name = "wasix-based-evm"
module = "wasix-based-evm"
runner = "https://webc.org/runner/wasi"

[command.annotations.wasi]
args = ["--verbose", "2", "--data-dir", "data-dir"]
env = ["RUST_LOG=info"]