[package]
name = "tester"
version = "0.1.0"
edition = "2024"

[dependencies]
hex = "0.4.3"
clap = { version = "4.6.0", features = ["derive"] }
rustyline = "18.0.0"
shlex = "1.3.0"
alloy-primitives = { version = "1.5.7", default-features = false, features = ["serde"] }
alloy-genesis = { version = "=1.6.3", default-features = false }
alloy-consensus = { version = "=1.6.3", default-features = false, features = ["k256", "std"] }
alloy-json-rpc = { version = "=1.6.3", default-features = false }
alloy-tx-macros = { version = "=1.6.3", default-features = false }
alloy-serde= { version = "=1.6.3", default-features = false }
alloy-eips = { version = "=1.6.3", default-features = false }
alloy-rpc-types = { version = "=1.6.3", default-features = false, features = ["eth", "engine", "admin", "txpool", "jsonrpsee-types"] }
alloy-trie = { version = "0.9.5", default-features = false, features = ["std"] }
alloy-rlp = { version = "0.3.15", default-features = false, features = ["derive"] }

# gRPC and WASIX dependencies

wasix = { version = "0.13.1" }
rand = "=0.8.5"
tokio = {version = "1.47.4", features = ["full"]}
jsonrpsee = {path = "../jsonrpsee/jsonrpsee", default-features = false, features = ["full"]}
