{
 "title": "Exemplary Monitoring Dashboard",
 "tags": [ "exemplary" ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Prometheus HTTP Requests Rate (5m)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(prometheus_http_requests_total[5m])"
    }
   ]
  },
  {
   "title": "Node Exporter: Available Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "node_memory_MemAvailable_bytes" }
   ]
  },
  {
   "title": "Metrics Server: Collection Ticks",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "metrics_server_collection_ticks_total"
    }
   ]
  }
 ]
}