[package]
name = "wasix_eth_core"
description = ""
version.workspace = true
authors.workspace = true
edition.workspace = true


[lints]
workspace = true

[dependencies]
wasix_eth_storage = {workspace = true}
wasix_eth_execution = { workspace = true}
wasix_eth_types = {workspace = true}
wasix_eth_utils = {workspace = true}
alloy-rlp = { workspace = true }
alloy-rpc-types  = {workspace = true}
tokio = { workspace = true }
alloy-signer-local = {workspace = true}
alloy-network = {workspace = true}
alloy-signer = {workspace = true}
anyhow = {workspace = true}
alloy-primitives = {workspace = true}
futures-util = {workspace = true}

serde_json = { workspace = true }
alloy-consensus = { workspace = true }
rand = { workspace = true }
dashmap = { workspace = true }
im = "15.1.0"

[target.'cfg(not(target_family = "wasm"))'.dev-dependencies]
tempfile = "3.10"
