[workspace]
members = [
    "wasix_eth_rpc",
    "wasix_eth_storage",
    "wasix_eth_types",
    "wasix_eth_execution",
    "wasix_eth_p2p",
    "wasix_eth_app",
    "wasix_eth_utils",
    "wasix_eth_core",
    #"testing",
]
resolver = "3"

[workspace.package]
version = "0.1.0"
edition = "2024"
authors = ["Z4l3s5i0"]

[workspace.lints.rust]
rust_2024_compatibility = { level = "warn", priority = -1 }

[profile.release]
panic = "abort"
lto = true
#codegen-units = 1

[workspace.dependencies]
wasix_eth_app = { path = "wasix_eth_app", version = "0.1.0" }
wasix_eth_utils = { path = "wasix_eth_utils", version = "0.1.0" }
wasix_eth_rpc = { path = "wasix_eth_rpc", version = "0.1.0" }
wasix_eth_storage = { path = "wasix_eth_storage", version = "0.1.0" }
wasix_eth_types = { path = "wasix_eth_types", version = "0.1.0" }
wasix_eth_execution = { path = "wasix_eth_execution", version = "0.1.0" }
wasix_eth_p2p = { path = "wasix_eth_p2p", version = "0.1.0" }
wasix_eth_core = { path = "wasix_eth_core", version = "0.1.0" }

clap = { version = "4.5.4", features = ["derive"] }
serde_json = { version = "1.0.0", default-features = false, features = ["alloc", "std"] }

once_cell = { version = "1.19.0" }
chrono = { version = "0.4" }

alloy-tx-macros = { version = "=1.6.3", default-features = false }
alloy-trie = { version = "0.9.5", default-features = false, features = ["std"] }
alloy-primitives = { version = "=1.5.7", default-features = false, features = ["serde"] }
alloy-genesis = { version = "=1.6.3", default-features = false }
alloy-consensus = { version = "=1.6.3", default-features = false, features = ["k256", "std"] }
alloy-eips = { version = "=1.6.3", default-features = false }
alloy-rpc-types = { version = "=1.6.3", default-features = false, features = ["eth", "engine", "admin", "txpool", "jsonrpsee-types"] }
anyhow = { version = "1.0.102", default-features = false }
serde = { version = "1.0.228", features = ["derive", "std", "serde_derive"] }

async-trait = { version = "0.1.89", default-features = false }

alloy-network = { version = "=1.6.3", default-features = false }
alloy-json-rpc = { version = "=1.6.3", default-features = false }
alloy-serde= { version = "=1.6.3", default-features = false }
alloy-rlp = { version = "=0.3.15", default-features = false, features = ["derive"] }

scopeguard = { version = "1.2", default-features =  false}


evm = { git = "https://github.com/Z4l3s5i0/evm.git", branch = "metrics", default-features = false, features = ["serde", "std"] }
evm-precompile = { git = "https://github.com/Z4l3s5i0/evm.git", branch = "metrics", default-features = false, features = ["std"] }
evm-interpreter = { git = "https://github.com/Z4l3s5i0/evm.git", branch = "metrics", default-features = false, features = ["serde", "std"] }
alloy-signer-local = { version = "=1.6.3", default-features = false }
alloy-signer = { version = "=1.6.3", default-features = false }

rand = { version = "=0.8.5", default-features = false }
getrandom = {git = "https://github.com/rust-random/getrandom", tag = "v0.2.15" , default-features = false}
mio = { git = "https://github.com/wasix-org/mio", default-features = false }
h2 = "0.4"
thiserror = "2.0.18"
hex = "0.4.3"
ecies = { version = "0.2.11",default-features = false, features = ["pure"]}
aes = "0.8.4"
ctr = "0.9.2"
snap = "1.1.1"
crc = "3.2.1"
quanta = { version = "0.12.6", default-features = false, features = ["default"] }
hmac = "0.12.1"
sha3 = { version = "0.10" }
sha2 = { version = "0.10" }
futures-util = "0.3.31"
http = "1.1.0"
base64 = "0.22.1"

k256 = { version = "0.13.1", features = ["ecdsa", "arithmetic", "ecdh"] }

# When using something different than wasix

#socket2 = { version="0.4.5" , default-features = false, features = ["all"]}
#tokio-rustls = { version = "0.24.1", default-features = false, features = ["logging", "tls12", "dangerous_configuration", "secret_extraction"] }
#reqwest = {version = "0.11.8", default-features = false, features = ["json", "serde_json"]}
#jsonrpsee = {version = "0.26.0", default-features = false, features = ["tracing", "server", "jsonrpsee-proc-macros", "jsonrpsee-core", "client-core", "jsonrpsee-types"]}
#rustls = { version = "0.23.31", default-features = false, features = [ "tls12"] }
#ring = { version = "0.17.7" }
#tokio = { version = "1.47.0", default-features = false, features = [ "rt-multi-thread", "rt", "macros", "sync", "time", "io-util", "net" ] }
#


redb = { version = "4.1.0", default-features = false }

tower = { version = "0.5.3", default-features = false, features = ["util"] }
tower-http = { version = "0.5.2", default-features = false, features = ["fs", "cors"] }
prometheus = {version = "0.14.0"}
lazy_static = {version = "1.5.0"}

# When using wasix

wasmer = { version = "7.1.0", default-features=false, features=["js-default"]}

wasix = { version = "0.13.1" }

ring = { git = "https://github.com/wasix-org/ring", branch = "0.17.7" }
reqwest = {git = "https://github.com/wasix-org/reqwest.git", branch = "rustls-0.21.8", default-features = false, features = ["json", "serde_json"]}
jsonrpsee = {git = "https://github.com/Z4l3s5i0/jsonrpsee", branch = "fix", default-features = false, features = ["server", "jsonrpsee-proc-macros", "jsonrpsee-core", "client-core", "jsonrpsee-types"]}
tokio = { git = "https://github.com/wasix-org/tokio.git", branch = "wasix-1.47.0", default-features = false, features = [ "rt-multi-thread", "rt", "macros", "sync", "time", "io-util", "net" ] }
tokio-rustls = { git = "https://github.com/wasix-org/tokio-rustls.git", branch = "main", default-features = false, features = ["logging", "tls12", "dangerous_configuration", "secret_extraction"] }
socket2 = { git = "https://github.com/wasix-org/socket2.git", branch = "wasix", default-features = false, features = ["all"]}
rustls = { git = "https://github.com/wasix-org/rustls.git", branch = "v0.21.8", default-features = false, features = ["tls12", "logging"] }


[patch.crates-io]
wasm-bindgen = {git = "https://github.com/wasix-org/wasm-bindgen.git" , branch = "wasi"}
getrandom = {git = "https://github.com/rust-random/getrandom", tag = "v0.2.15" }
mio = { git = "https://github.com/wasix-org/mio" }
#parking_lot = { path = "../parking_lot" }

h2 = { git = "https://github.com/wasix-org/h2", branch = "wasix-0.4.12" }
hyper = { git = "https://github.com/wasix-org/hyper", branch = "v0.14.28" }
ring = {git = "https://github.com/wasix-org/ring", branch = "0.17.7"}
rustls = { git = "https://github.com/wasix-org/rustls.git", branch = "wasix-0.23.31" }
tokio = { git = "https://github.com/wasix-org/tokio.git", branch = "wasix-1.47.0" }
socket2 = { git = "https://github.com/wasix-org/socket2", branch = "wasix" }

tokio-rustls = { git = "https://github.com/wasix-org/tokio-rustls.git", branch = "main" }
libc = { git = "https://github.com/john-sharratt/libc.git", rev = "682f9e91" }


