services:
  wasix-eth-linux:
    build:
      context: .
      dockerfile: Dockerfile.linux
    volumes:
      - ./data/linux:/app/data
      - ./startup:/app/startup
    ports:
      - "8545:8545" # Eth JSON-RPC
      - "8551:8551" # Auth Engine JSON-RPC
      - "30303:30303/udp" # P2P discovery
      - "30304:30304" # P2P gossip
      - "3000:3000" # Frontend
      - "9050:9050" # Metrics
    command: ["run", "--data-dir", "/app/data", "--genesis-path", "/app/startup/genesis.json", "--peer-name", "linux-node", "--eth-rpc-port", "8545", "--auth-rpc-port", "8551", "--p2p-port", "30304", "--discovery-port", "30303", "--frontend-port", "3000", "--metrics-port", "9050"]

  wasix-eth-windows:
    build:
      context: .
      dockerfile: Dockerfile.windows
    volumes:
      - ./data/windows:/app/data
      - ./startup:/app/startup
    ports:
      - "8546:8546" # Eth JSON-RPC
      - "8552:8552" # Auth Engine JSON-RPC
      - "30305:30305/udp" # P2P discovery
      - "30306:30306" # P2P gossip
      - "3001:3001" # Frontend
      - "9051:9051" # Metrics
    command: ["run", "--data-dir", "/app/data", "--genesis-path", "/app/startup/genesis.json", "--peer-name", "windows-node", "--eth-rpc-port", "8546", "--auth-rpc-port", "8552", "--p2p-port", "30306", "--discovery-port", "30305", "--frontend-port", "3001", "--metrics-port", "9051"]

  wasix-eth-wasix:
    build:
      context: .
      dockerfile: Dockerfile.wasix
    volumes:
      - ./data/wasix:/app/data
      - ./startup:/app/startup
    ports:
      - "8547:8547" # Eth JSON-RPC
      - "8553:8553" # Auth Engine JSON-RPC
      - "30307:30307/udp" # P2P discovery
      - "30308:30308" # P2P gossip
      - "3002:3002" # Frontend
      - "9052:9052" # Metrics
    command: ["run", "--data-dir", "/app/data", "--genesis-path", "/app/startup/genesis.json", "--peer-name", "wasix-node", "--eth-rpc-port", "8547", "--auth-rpc-port", "8553", "--p2p-port", "30308", "--discovery-port", "30307", "--frontend-port", "3002", "--metrics-port", "9052"]

  metrics-server:
    build:
      context: ../metrics_server
      dockerfile: Dockerfile
    ports:
      - "9100:9100"
    volumes:
      - ../metrics_server/config:/app/config
      - ../metrics_server/data:/app/data
    depends_on:
      - wasix-eth-linux
      - wasix-eth-windows
      - wasix-eth-wasix
